BookShop/Controllers/BooksController.cs
using BookShop.Application;
using BookShop.Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using System.IO;
using BookShop.Models;

namespace BookShop.Controllers
{
    public class BooksController : Controller
    {
        private readonly ILogger<GenresController> _logger;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IBookRepository _bookRepository;
        private readonly IAuthorRepository _authorRepository;
        private readonly IBookGenreRepository _bookGenreRepository;
        private readonly IBookAuthorRepository _bookAuthorRepository;


        public BooksController(
            ILogger<GenresController> logger,
            IBookRepository bookRepository,
            ICategoryRepository categoryRepository,
            IAuthorRepository authorRepository,
            IBookGenreRepository bookGenreRepository,
            IBookAuthorRepository bookAuthorRepository)
        {
            _logger = logger;
            _categoryRepository = categoryRepository;
            _bookRepository = bookRepository;
            _authorRepository = authorRepository;
            _bookGenreRepository = bookGenreRepository;
            _bookAuthorRepository = bookAuthorRepository;
        }

        // GET: BookController
        public async Task<ActionResult> Index()
        {
            // Переделать через ViewModel
            return View(await _bookRepository.GetFullData());
        }

        // GET: BookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BookController/Create
        public async Task<ActionResult> Create(int id)
        {
            CreateBookViewModel bookModel = new CreateBookViewModel()
            {
                Id = id,
                Book = await _bookRepository.GetById(id),
                Authors = await _authorRepository.GetAll(),
                Genres = await _categoryRepository.GetAll()
            };
            //IEnumerable<Author> authors = await _authorRepository.GetAll();
            //ViewBag.AuthorsList = authors;
            //ViewBag.GenresList = await _categoryRepository.GetAll();

            ViewBag.SelectListGenres = new SelectList(await _categoryRepository.GetAll(), "Id", "Name");
            ViewBag.SelectListAuthors = (IEnumerable<SelectListItem>)_authorRepository.ToSelectListItems(bookModel.Authors, 0);


            return View(bookModel);
        }

        // POST: BookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Book book, int genreId, int authorId, IFormCollection collection)
        {
            try
            {
                await _bookRepository.Insert(book);
                await _bookGenreRepository.Insert(new BookGenre
                {
                    Book = book,
                    Genre = await _categoryRepository.GetById(genreId)
                });
                await _bookAuthorRepository.Insert(new BookAuthor
                {
                    Book = book,
                    Author = await _authorRepository.GetById(authorId)
                });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View();
        }

        // POST: BookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BookController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View();
        }

        // POST: BookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookShop/Controllers/GenresController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BookShop.Infrastructure;
using BookShop.Application;
using BookShop.Domain;
using System.Collections.Generic;
using System.Linq;
using BookShop.Filters;

namespace BookShop.Controllers
{
    public class GenresController : Controller
    {
        //private readonly IStoreService store;
        private readonly ILogger<GenresController> _logger;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IBookRepository _bookRepository;

        public GenresController(
            IBookRepository bookRepository,
            ILogger<GenresController> logger,
            ICategoryRepository categoryRepository)
        {
            //this.store = store;
            this._logger = logger;
            this._categoryRepository = categoryRepository;
            this._bookRepository = bookRepository;
        }

        // GET: GenresController
        public async Task<ActionResult> Index()
        {
            ViewBag.Categories = await _categoryRepository.GetAll();

            return View(await _categoryRepository.GetAll());
        }
        
        public async Task<ActionResult> Genre(int id)
        {
            ViewBag.BooksList = await _bookRepository.GetBooksFromCategory(id);

            return View(await _categoryRepository.GetById(id));
        }

        // GET: GenresController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View(await _categoryRepository.GetById(id));
        }

        // GET: GenresController/Create
        public async Task<ActionResult> Create()
        {
            return View();
        }

        // POST: GenresController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Genre newGenre)
        {
            try
            {
                await _categoryRepository.Insert(newGenre);
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GenresController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            Genre genre = await _categoryRepository.GetById(id);
            return View(genre);
        }

        // POST: GenresController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Genre editedGenre, IFormCollection collection)
        {
            try
            {
                await _categoryRepository.Update(editedGenre);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GenresController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            Genre genre = await _categoryRepository.GetById(id);
            if (genre == null)
            {
                return RedirectToRoute("Share", "Error");
            }
            return View(genre);

        }

        // POST: GenresController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            await _categoryRepository.Delete(id);

            return RedirectToAction(nameof(Index));

        }
    }
}

BookShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genres" asp-action="Index">Жанры</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Все Книги</a>
                        </li>
                    </ul>
                </div>
                <form class="d-flex" role="search">
                    <input class="form-control rounded-2 me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-primary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>